[project]
name = "bacon-and-eggs"
version = "2024.0.0"
requires-python = ">=3.12"
authors = [
 { name = "Jay Cruz", email = "jmcruz14@gmail.com" }
]
dependencies = [
    "fastapi[standard]>=0.115.3",
]
